name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *' # 每天UTC时间0点执行
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 新增权限用于创建 PR
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add Upstream
        run: git remote add upstream https://github.com/celesWuff/waterctl.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Merge Upstream
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git merge upstream/2.x --no-edit
          git checkout -b sync/upstream-$(date +%s) 

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Sync upstream changes"
          title: "Sync upstream changes from 2.x branch"
          body: "Automated PR syncing upstream changes"
          branch: "sync/upstream"  # 分支基础名称
          base: main  # 目标分支
          labels: automated,upstream-sync